package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const skillDir = ".agents/skills/devctl-cli"
const skillFile = "SKILL.md"

func init() {
	Register(&Cmd{
		Name:        "devctl:skill",
		Description: "Generate an OpenCode agent skill describing all CLI commands",
		Usage:       "[--output=path]",
		Flags: []FlagDef{
			{
				Name:        "output",
				Default:     "~/.agents/skills/devctl-cli/SKILL.md",
				Description: "Path to write the skill file",
			},
		},
		Examples: []string{
			"devctl devctl:skill",
			"devctl devctl:skill --output=/custom/path/SKILL.md",
		},
		Handler: func(c *Client, args []string, jsonMode bool) error {
			outputPath := ""
			for _, a := range args {
				if strings.HasPrefix(a, "--output=") {
					outputPath = strings.TrimPrefix(a, "--output=")
				}
			}
			if outputPath == "" {
				home, err := userHome()
				if err != nil {
					return fmt.Errorf("cannot determine home directory: %w", err)
				}
				outputPath = filepath.Join(home, skillDir, skillFile)
			}
			// Expand ~ manually if needed
			if strings.HasPrefix(outputPath, "~/") {
				home, err := userHome()
				if err != nil {
					return fmt.Errorf("cannot determine home directory: %w", err)
				}
				outputPath = filepath.Join(home, outputPath[2:])
			}

			if err := WriteSkill(outputPath); err != nil {
				return err
			}
			if jsonMode {
				PrintJSON(map[string]string{"status": "ok", "path": outputPath})
				return nil
			}
			PrintOK("Skill written to " + outputPath)
			return nil
		},
	})
}

// DefaultSkillPath returns the default path for the CLI skill file.
func DefaultSkillPath() (string, error) {
	home, err := userHome()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, skillDir, skillFile), nil
}

// SkillInstalled reports whether the CLI skill file already exists.
func SkillInstalled() bool {
	path, err := DefaultSkillPath()
	if err != nil {
		return false
	}
	_, err = os.Stat(path)
	return err == nil
}

// WriteSkill generates the SKILL.md at the given path, creating parent dirs.
func WriteSkill(outputPath string) error {
	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		return fmt.Errorf("create skill directory: %w", err)
	}
	content := generateSkillContent()
	if err := os.WriteFile(outputPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write skill file: %w", err)
	}
	return nil
}

// UpdateSkillIfInstalled silently regenerates the skill file if it exists.
// Safe to call in a goroutine on daemon startup.
func UpdateSkillIfInstalled() {
	path, err := DefaultSkillPath()
	if err != nil {
		return
	}
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return
	}
	_ = WriteSkill(path)
}

// generateSkillContent builds the SKILL.md content from the command registry.
func generateSkillContent() string {
	var sb strings.Builder
	now := time.Now().Format("2006-01-02")

	sb.WriteString("# Skill: devctl-cli\n\n")
	sb.WriteString("<!-- Auto-generated by `devctl devctl:skill` on " + now + " — do not edit manually -->\n\n")
	sb.WriteString("## Overview\n\n")
	sb.WriteString("devctl is a local PHP development environment manager for Linux. ")
	sb.WriteString("This skill documents the devctl CLI — all commands communicate with the running ")
	sb.WriteString("devctl daemon at `127.0.0.1:4000` (or `$DEVCTL_ADDR`) without requiring root.\n\n")
	sb.WriteString("## Quick start\n\n")
	sb.WriteString("```sh\n")
	sb.WriteString("devctl services:list              # see all services and status\n")
	sb.WriteString("devctl sites:list                 # see all sites\n")
	sb.WriteString("devctl logs:tail caddy            # stream Caddy log tail\n")
	sb.WriteString("devctl services:restart caddy     # restart a service\n")
	sb.WriteString("sudo devctl daemon                # start the daemon (requires root, managed by systemd)\n")
	sb.WriteString("```\n\n")
	sb.WriteString("## Global flags\n\n")
	sb.WriteString("| Flag | Description |\n")
	sb.WriteString("|---|---|\n")
	sb.WriteString("| `--json` | Output raw JSON instead of formatted text |\n")
	sb.WriteString("| `--addr=host:port` | Daemon address (default: `127.0.0.1:4000`, or `$DEVCTL_ADDR`) |\n")
	sb.WriteString("| `--help` | Show help for a specific command |\n\n")

	// Group by namespace
	groups := map[string][]*Cmd{}
	var namespaces []string
	for _, cmd := range All() {
		parts := strings.SplitN(cmd.Name, ":", 2)
		ns := parts[0]
		if _, ok := groups[ns]; !ok {
			namespaces = append(namespaces, ns)
		}
		groups[ns] = append(groups[ns], cmd)
	}
	// Sort namespaces in a logical order
	nsOrder := []string{"services", "sites", "php", "logs", "dumps", "spx", "mail", "dns", "tls", "settings", "devctl"}
	seen := map[string]bool{}
	ordered := []string{}
	for _, ns := range nsOrder {
		if _, ok := groups[ns]; ok {
			ordered = append(ordered, ns)
			seen[ns] = true
		}
	}
	for _, ns := range namespaces {
		if !seen[ns] {
			ordered = append(ordered, ns)
		}
	}

	for _, ns := range ordered {
		cmds := groups[ns]
		sb.WriteString("## " + ns + ": commands\n\n")

		for _, cmd := range cmds {
			sb.WriteString("### `devctl " + cmd.Name)
			if cmd.Usage != "" {
				sb.WriteString(" " + cmd.Usage)
			}
			sb.WriteString("`\n\n")
			sb.WriteString(cmd.Description + "\n\n")

			if len(cmd.Args) > 0 {
				sb.WriteString("**Arguments:**\n\n")
				for _, a := range cmd.Args {
					opt := ""
					if a.Optional {
						opt = " *(optional)*"
					}
					sb.WriteString(fmt.Sprintf("- `%s` — %s%s\n", a.Name, a.Description, opt))
				}
				sb.WriteString("\n")
			}

			if len(cmd.Flags) > 0 {
				sb.WriteString("**Flags:**\n\n")
				for _, f := range cmd.Flags {
					def := ""
					if f.Default != "" {
						def = fmt.Sprintf(" (default: `%s`)", f.Default)
					}
					sb.WriteString(fmt.Sprintf("- `--%s` — %s%s\n", f.Name, f.Description, def))
				}
				sb.WriteString("\n")
			}

			if len(cmd.Examples) > 0 {
				sb.WriteString("```sh\n")
				for _, e := range cmd.Examples {
					sb.WriteString(e + "\n")
				}
				sb.WriteString("```\n\n")
			}
		}
	}

	sb.WriteString("## Notes\n\n")
	sb.WriteString("- Service IDs: `caddy`, `redis`, `postgres`, `mysql`, `mailpit`, `meilisearch`, `typesense`, `reverb`, `dns`. PHP-FPM services use `php-fpm-{version}` e.g. `php-fpm-8.3`.\n")
	sb.WriteString("- After updating PHP settings, restart the relevant FPM: `devctl services:restart php-fpm-8.3`\n")
	sb.WriteString("- The `--json` flag works on every command and is useful for scripting or piping to `jq`.\n")
	sb.WriteString("- The daemon runs at `http://127.0.0.1:4000`. All CLI commands proxy through it — no root required.\n")

	return sb.String()
}

func userHome() (string, error) {
	// Prefer SUDO_USER's home when running under sudo
	if sudoUser := os.Getenv("SUDO_USER"); sudoUser != "" {
		// Look up the real user's home
		homeBase := "/home/" + sudoUser
		if _, err := os.Stat(homeBase); err == nil {
			return homeBase, nil
		}
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return home, nil
}
