package config

import "github.com/danielgormly/devctl/services"

// DefaultServices returns the built-in service definitions.
// siteHome is the home directory of the non-root site user (e.g. "/home/alice").
// siteUser is the username of that user (e.g. "alice") — required for services
// that must not run as root (e.g. PostgreSQL uses ManagedUser to drop privs).
func DefaultServices(siteHome, siteUser string) []services.Definition {
	caddyDir := siteHome + "/sites/server/caddy"
	meiliDir := siteHome + "/sites/server/meilisearch"
	tsDir := siteHome + "/sites/server/typesense"
	valkeyDir := siteHome + "/sites/server/valkey"
	mailpitDir := siteHome + "/sites/server/mailpit"
	mysqlDir := siteHome + "/sites/server/mysql"
	postgresDir := siteHome + "/sites/server/postgres"
	return []services.Definition{
		{
			ID:             "caddy",
			Label:          "Caddy",
			Description:    "Fast, production-ready reverse proxy and TLS terminator",
			InstallVersion: "v2.10.0",
			Installable:    true,
			Required:       true,
			Managed:        true,
			ManagedCmd:     caddyDir + "/caddy",
			ManagedArgs:    "run --resume",
			ManagedDir:     caddyDir,
			ManagedEnvFile: caddyDir + "/caddy.env",
			Version:        caddyDir + "/caddy version",
			VersionRegex:   `v(?P<version>[\d.]+)`,
			Log:            caddyDir + "/caddy.log",
			HealthCheck:    "curl -sf http://localhost:2019/config/",
		},
		{
			ID:              "redis",
			Label:           "Valkey",
			Description:     "High-performance Redis-compatible in-memory data store",
			InstallVersion:  "9.0.3",
			Installable:     true,
			HasCredentials:  true,
			Managed:         true,
			ManagedCmd:      valkeyDir + "/valkey-server",
			ManagedArgs:     "--bind 127.0.0.1 --port 6379 --daemonize no",
			ManagedDir:      valkeyDir,
			Version:         valkeyDir + "/valkey-server --version",
			VersionRegex:    `v=(?P<version>[\d.]+)`,
			CredentialsFile: valkeyDir + "/config.env",
			Log:             valkeyDir + "/valkey.log",
		},
		{
			ID:              "postgres",
			Label:           "PostgreSQL",
			Description:     "Powerful open-source relational database",
			InstallVersion:  "18.3",
			Installable:     true,
			HasCredentials:  true,
			Managed:         true,
			ManagedCmd:      postgresDir + "/bin/postgres",
			ManagedArgs:     "-D " + postgresDir + "/data",
			ManagedDir:      postgresDir,
			ManagedUser:     siteUser,
			Version:         postgresDir + "/bin/postgres --version",
			VersionRegex:    `(?P<version>[\d.]+)`,
			CredentialsFile: postgresDir + "/config.env",
			Log:             postgresDir + "/postgres.log",
			HealthCheck:     postgresDir + "/bin/pg_isready -h 127.0.0.1 -p 5432 -U " + siteUser + " -d postgres",
		},
		{
			ID:              "mysql",
			Label:           "MySQL",
			Description:     "Popular open-source relational database",
			InstallVersion:  "8.4.7",
			Installable:     true,
			HasCredentials:  true,
			Managed:         true,
			ManagedCmd:      mysqlDir + "/bin/mysqld",
			ManagedArgs:     "--defaults-file=./my.cnf --user=root",
			ManagedDir:      mysqlDir,
			Version:         mysqlDir + "/bin/mysql --version",
			VersionRegex:    `(?P<version>[\d.]+)`,
			CredentialsFile: mysqlDir + "/config.env",
			Log:             mysqlDir + "/mysql-error.log",
			HealthCheck:     mysqlDir + "/bin/mysqladmin --socket=" + mysqlDir + "/mysql.sock ping",
		},
		{
			ID:             "meilisearch",
			Label:          "Meilisearch",
			Description:    "Lightning-fast search engine with instant results",
			InstallVersion: "v1.37.0",
			Installable:    true,
			HasCredentials: true,
			Managed:        true,
			ManagedCmd:     meiliDir + "/meilisearch",
			ManagedArgs:    "--http-addr 127.0.0.1:7700 --no-analytics --db-path ./data.ms",
			ManagedDir:     meiliDir,
			ManagedEnvFile: meiliDir + "/config.env",
			Version:        meiliDir + "/meilisearch --version",
			VersionRegex:   `meilisearch (?P<version>[\d.]+)`,
			Log:            meiliDir + "/meilisearch.log",
		},
		{
			ID:             "typesense",
			Label:          "Typesense",
			Description:    "Open-source typo-tolerant search engine",
			InstallVersion: "30.1",
			Installable:    true,
			HasCredentials: true,
			Managed:        true,
			ManagedCmd:     tsDir + "/typesense-server",
			ManagedArgs:    "--data-dir ./data --listen-port 8108 --enable-cors",
			ManagedDir:     tsDir,
			ManagedEnvFile: tsDir + "/config.env",
			Version:        tsDir + "/typesense-server --version",
			VersionRegex:   `Typesense (?P<version>[\d.]+)`,
			Log:            tsDir + "/typesense.log",
		},
		{
			ID:              "mailpit",
			Label:           "Mailpit",
			Description:     "Email testing tool with SMTP server and web UI",
			InstallVersion:  "v1.29.2",
			Installable:     true,
			HasCredentials:  true,
			Managed:         true,
			ManagedCmd:      mailpitDir + "/mailpit",
			ManagedArgs:     "--listen 127.0.0.1:8025 --smtp 127.0.0.1:1025 --database ./data/mailpit.db",
			ManagedDir:      mailpitDir,
			Version:         mailpitDir + "/mailpit version",
			VersionRegex:    `v(?P<version>[\d.]+)`,
			CredentialsFile: mailpitDir + "/config.env",
			Log:             mailpitDir + "/mailpit.log",
		},
		{
			ID:             "reverb",
			Label:          "Laravel Reverb",
			Description:    "First-party WebSocket server for Laravel applications",
			InstallVersion: "latest",
			Installable:    true,
			Managed:        true,
			ManagedCmd:     "php",
			ManagedArgs:    "artisan reverb:start --host=127.0.0.1 --port=7383",
			Version:        `grep -m1 '"version"' ` + siteHome + `/sites/reverb/vendor/laravel/reverb/composer.json`,
			VersionRegex:   `"version": "(?P<version>[^"]+)"`,
			Log:            siteHome + "/sites/reverb/storage/logs/laravel.log",
			// Start/Stop/Restart/Status are handled by the Supervisor, not shell commands.
		},
	}
}
