// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dumps.sql

package dbq

import (
	"context"
)

const countDumps = `-- name: CountDumps :one
SELECT COUNT(*) FROM dumps
`

func (q *Queries) CountDumps(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDumps)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDumpsBySite = `-- name: CountDumpsBySite :one
SELECT COUNT(*) FROM dumps WHERE site_domain = ?
`

func (q *Queries) CountDumpsBySite(ctx context.Context, siteDomain *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDumpsBySite, siteDomain)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllDumps = `-- name: DeleteAllDumps :exec
DELETE FROM dumps
`

func (q *Queries) DeleteAllDumps(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllDumps)
	return err
}

const getDumps = `-- name: GetDumps :many
SELECT id, file, line, nodes, timestamp, site_domain FROM dumps
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type GetDumpsParams struct {
	Limit  int64 `db:"limit" json:"limit"`
	Offset int64 `db:"offset" json:"offset"`
}

func (q *Queries) GetDumps(ctx context.Context, arg GetDumpsParams) ([]Dump, error) {
	rows, err := q.db.QueryContext(ctx, getDumps, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dump{}
	for rows.Next() {
		var i Dump
		if err := rows.Scan(
			&i.ID,
			&i.File,
			&i.Line,
			&i.Nodes,
			&i.Timestamp,
			&i.SiteDomain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDumpsBySite = `-- name: GetDumpsBySite :many
SELECT id, file, line, nodes, timestamp, site_domain FROM dumps
WHERE site_domain = ?
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type GetDumpsBySiteParams struct {
	SiteDomain *string `db:"site_domain" json:"site_domain"`
	Limit      int64   `db:"limit" json:"limit"`
	Offset     int64   `db:"offset" json:"offset"`
}

func (q *Queries) GetDumpsBySite(ctx context.Context, arg GetDumpsBySiteParams) ([]Dump, error) {
	rows, err := q.db.QueryContext(ctx, getDumpsBySite, arg.SiteDomain, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dump{}
	for rows.Next() {
		var i Dump
		if err := rows.Scan(
			&i.ID,
			&i.File,
			&i.Line,
			&i.Nodes,
			&i.Timestamp,
			&i.SiteDomain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDump = `-- name: InsertDump :one
INSERT INTO dumps (file, line, nodes, timestamp, site_domain)
VALUES (?, ?, ?, ?, ?)
RETURNING id, file, line, nodes, timestamp, site_domain
`

type InsertDumpParams struct {
	File       *string `db:"file" json:"file"`
	Line       *int64  `db:"line" json:"line"`
	Nodes      string  `db:"nodes" json:"nodes"`
	Timestamp  float64 `db:"timestamp" json:"timestamp"`
	SiteDomain *string `db:"site_domain" json:"site_domain"`
}

func (q *Queries) InsertDump(ctx context.Context, arg InsertDumpParams) (Dump, error) {
	row := q.db.QueryRowContext(ctx, insertDump,
		arg.File,
		arg.Line,
		arg.Nodes,
		arg.Timestamp,
		arg.SiteDomain,
	)
	var i Dump
	err := row.Scan(
		&i.ID,
		&i.File,
		&i.Line,
		&i.Nodes,
		&i.Timestamp,
		&i.SiteDomain,
	)
	return i, err
}

const pruneOldDumps = `-- name: PruneOldDumps :exec
DELETE FROM dumps WHERE id NOT IN (
    SELECT id FROM dumps ORDER BY id DESC LIMIT ?
)
`

func (q *Queries) PruneOldDumps(ctx context.Context, limit int64) error {
	_, err := q.db.ExecContext(ctx, pruneOldDumps, limit)
	return err
}
