// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbq

import (
	"time"
)

type Dump struct {
	ID         int64   `db:"id" json:"id"`
	File       *string `db:"file" json:"file"`
	Line       *int64  `db:"line" json:"line"`
	Nodes      string  `db:"nodes" json:"nodes"`
	Timestamp  float64 `db:"timestamp" json:"timestamp"`
	SiteDomain *string `db:"site_domain" json:"site_domain"`
}

type Setting struct {
	Key   string `db:"key" json:"key"`
	Value string `db:"value" json:"value"`
}

type Site struct {
	ID             string    `db:"id" json:"id"`
	Domain         string    `db:"domain" json:"domain"`
	RootPath       string    `db:"root_path" json:"root_path"`
	PhpVersion     string    `db:"php_version" json:"php_version"`
	Aliases        string    `db:"aliases" json:"aliases"`
	SpxEnabled     int64     `db:"spx_enabled" json:"spx_enabled"`
	Https          int64     `db:"https" json:"https"`
	AutoDiscovered int64     `db:"auto_discovered" json:"auto_discovered"`
	Settings       string    `db:"settings" json:"settings"`
	ParentSiteID   *string   `db:"parent_site_id" json:"parent_site_id"`
	WorktreeBranch *string   `db:"worktree_branch" json:"worktree_branch"`
	PublicDir      string    `db:"public_dir" json:"public_dir"`
	ServiceVhost   int64     `db:"service_vhost" json:"service_vhost"`
	IsGitRepo      int64     `db:"is_git_repo" json:"is_git_repo"`
	GitRemoteURL   string    `db:"git_remote_url" json:"git_remote_url"`
	Framework      string    `db:"framework" json:"framework"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
}
