// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sites.sql

package dbq

import (
	"context"
)

const createSite = `-- name: CreateSite :one
INSERT INTO sites (id, domain, root_path, php_version, aliases, spx_enabled, https, auto_discovered, settings)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, domain, root_path, php_version, aliases, spx_enabled, https, auto_discovered, settings, created_at, updated_at
`

type CreateSiteParams struct {
	ID             string `db:"id" json:"id"`
	Domain         string `db:"domain" json:"domain"`
	RootPath       string `db:"root_path" json:"root_path"`
	PhpVersion     string `db:"php_version" json:"php_version"`
	Aliases        string `db:"aliases" json:"aliases"`
	SpxEnabled     int64  `db:"spx_enabled" json:"spx_enabled"`
	Https          int64  `db:"https" json:"https"`
	AutoDiscovered int64  `db:"auto_discovered" json:"auto_discovered"`
	Settings       string `db:"settings" json:"settings"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRowContext(ctx, createSite,
		arg.ID,
		arg.Domain,
		arg.RootPath,
		arg.PhpVersion,
		arg.Aliases,
		arg.SpxEnabled,
		arg.Https,
		arg.AutoDiscovered,
		arg.Settings,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.RootPath,
		&i.PhpVersion,
		&i.Aliases,
		&i.SpxEnabled,
		&i.Https,
		&i.AutoDiscovered,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSite = `-- name: DeleteSite :exec
DELETE FROM sites WHERE id = ?
`

func (q *Queries) DeleteSite(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSite, id)
	return err
}

const getAllSites = `-- name: GetAllSites :many
SELECT id, domain, root_path, php_version, aliases, spx_enabled, https, auto_discovered, settings, created_at, updated_at FROM sites ORDER BY created_at ASC
`

func (q *Queries) GetAllSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.QueryContext(ctx, getAllSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.RootPath,
			&i.PhpVersion,
			&i.Aliases,
			&i.SpxEnabled,
			&i.Https,
			&i.AutoDiscovered,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSite = `-- name: GetSite :one
SELECT id, domain, root_path, php_version, aliases, spx_enabled, https, auto_discovered, settings, created_at, updated_at FROM sites WHERE id = ? LIMIT 1
`

func (q *Queries) GetSite(ctx context.Context, id string) (Site, error) {
	row := q.db.QueryRowContext(ctx, getSite, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.RootPath,
		&i.PhpVersion,
		&i.Aliases,
		&i.SpxEnabled,
		&i.Https,
		&i.AutoDiscovered,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteByDomain = `-- name: GetSiteByDomain :one
SELECT id, domain, root_path, php_version, aliases, spx_enabled, https, auto_discovered, settings, created_at, updated_at FROM sites WHERE domain = ? LIMIT 1
`

func (q *Queries) GetSiteByDomain(ctx context.Context, domain string) (Site, error) {
	row := q.db.QueryRowContext(ctx, getSiteByDomain, domain)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.RootPath,
		&i.PhpVersion,
		&i.Aliases,
		&i.SpxEnabled,
		&i.Https,
		&i.AutoDiscovered,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSiteSPX = `-- name: SetSiteSPX :exec
UPDATE sites SET spx_enabled = ?, updated_at = datetime('now') WHERE id = ?
`

type SetSiteSPXParams struct {
	SpxEnabled int64  `db:"spx_enabled" json:"spx_enabled"`
	ID         string `db:"id" json:"id"`
}

func (q *Queries) SetSiteSPX(ctx context.Context, arg SetSiteSPXParams) error {
	_, err := q.db.ExecContext(ctx, setSiteSPX, arg.SpxEnabled, arg.ID)
	return err
}

const updateSite = `-- name: UpdateSite :one
UPDATE sites
SET domain = ?, root_path = ?, php_version = ?, aliases = ?, spx_enabled = ?, https = ?, settings = ?, updated_at = datetime('now')
WHERE id = ?
RETURNING id, domain, root_path, php_version, aliases, spx_enabled, https, auto_discovered, settings, created_at, updated_at
`

type UpdateSiteParams struct {
	Domain     string `db:"domain" json:"domain"`
	RootPath   string `db:"root_path" json:"root_path"`
	PhpVersion string `db:"php_version" json:"php_version"`
	Aliases    string `db:"aliases" json:"aliases"`
	SpxEnabled int64  `db:"spx_enabled" json:"spx_enabled"`
	Https      int64  `db:"https" json:"https"`
	Settings   string `db:"settings" json:"settings"`
	ID         string `db:"id" json:"id"`
}

func (q *Queries) UpdateSite(ctx context.Context, arg UpdateSiteParams) (Site, error) {
	row := q.db.QueryRowContext(ctx, updateSite,
		arg.Domain,
		arg.RootPath,
		arg.PhpVersion,
		arg.Aliases,
		arg.SpxEnabled,
		arg.Https,
		arg.Settings,
		arg.ID,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.RootPath,
		&i.PhpVersion,
		&i.Aliases,
		&i.SpxEnabled,
		&i.Https,
		&i.AutoDiscovered,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
